# TODO (ames0k0)
# - Set the images version
# - Change the Services and Containers name

services:

  stb--kafka_broker:
    image: apache/kafka:latest
    container_name: stb--kafka_broker
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://stb--kafka_broker:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://stb--kafka_broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "stb_events"
      AUTO_CREATE_TOPICS: "true"
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "stb--kafka_broker:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  stb--rabbitmq:
    image: rabbitmq:latest
    container_name: stb--rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  stb--redis:
    image: redis:latest
    container_name: stb--redis
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

  stb--minio:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    container_name: stb--minio
    command: ["minio", "server", "data"]

  stb--postgres:
    image: postgres
    container_name: stb--postgres
    environment:
      POSTGRES_PASSWORD: simple
      POSTGRES_DB: small_tool_box
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d small_tool_box"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: unless-stopped

  stb__core:
    build:
      context: stb__core
    image: stb__core:v0.1.0
    container_name: stb__core

  stb__tg_bot:
    build:
      context: .
    image: stb__tg_bot:v0.1.0
    container_name: stb__tg_bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      stb--kafka_broker:
        condition: service_healthy
      stb--rabbitmq:
        condition: service_healthy
      stb__core:
        condition: service_completed_successfully

  stb__tg_messages:
    build:
      context: stb__tg_messages
    image: stb__tg_messages:v0.1.0
    container_name: stb__tg_messages
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      stb--rabbitmq:
        condition: service_healthy
      stb--redis:
        condition: service_started
      stb--minio:
        condition: service_started
      stb__core:
        condition: service_completed_successfully

  stb__stats_generator:
    build:
      context: stb__stats_generator
    image: stb__stats_generator:v0.1.0
    container_name: stb__stats_generator
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      stb--postgres:
        condition: service_healthy
      stb__tg_messages:
        condition: service_started

  stb__events_analyzer:
    build:
      context: stb__events_analyzer
    image: stb__events_analyzer:v0.1.0
    container_name: stb__events_analyzer
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      stb--kafka_broker:
        condition: service_healthy
      stb--postgres:
        condition: service_healthy
